import yaml from 'js-yaml';

export const formatJson = (json: string, space: number = 2): string => {
  try {
    const obj = JSON.parse(json);
    return JSON.stringify(obj, null, space);
  } catch (e) {
    throw new Error('Invalid JSON');
  }
};

export const minifyJson = (json: string): string => {
  try {
    const obj = JSON.parse(json);
    return JSON.stringify(obj);
  } catch (e) {
    throw new Error('Invalid JSON');
  }
};

export const jsonToYaml = (json: string): string => {
  try {
    const obj = JSON.parse(json);
    return yaml.dump(obj);
  } catch (e) {
    throw new Error('Invalid JSON');
  }
};

export const yamlToJson = (yml: string): string => {
  try {
    const obj = yaml.load(yml);
    return JSON.stringify(obj, null, 2);
  } catch (e) {
    throw new Error('Invalid YAML');
  }
};

export const jsonToTypeScript = (json: string, interfaceName: string = 'RootObject'): string => {
  try {
    const obj = JSON.parse(json);
    let result = `export interface ${interfaceName} {\n`;
    
    if (typeof obj !== 'object' || obj === null) {
      return `export type ${interfaceName} = ${typeof obj};`;
    }

    Object.entries(obj).forEach(([key, value]) => {
      let type: string = typeof value;
      if (value === null) type = 'any';
      else if (Array.isArray(value)) {
        const itemType = value.length > 0 ? typeof value[0] : 'any';
        type = `${itemType}[]`;
      } else if (type === 'object') {
        type = 'Record<string, any>';
      }
      result += `  ${key}: ${type};\n`;
    });

    result += '}';
    return result;
  } catch (e) {
    throw new Error('Invalid JSON');
  }
};

export const jsonToGo = (json: string, structName: string = 'AutoGenerated'): string => {
  try {
    const obj = JSON.parse(json);
    let result = `type ${structName} struct {\n`;
    
    if (typeof obj !== 'object' || obj === null) {
      return `// Input is not an object`;
    }

    Object.entries(obj).forEach(([key, value]) => {
      const capitalizedKey = key.charAt(0).toUpperCase() + key.slice(1);
      let type: string = typeof value;
      if (value === null) type = 'interface{}';
      else if (Array.isArray(value)) {
        const itemType = value.length > 0 ? (typeof value[0] === 'number' ? 'float64' : typeof value[0]) : 'interface{}';
        type = `[]${itemType}`;
      } else if (type === 'number') {
        type = 'float64';
      } else if (type === 'object') {
        type = 'map[string]interface{}';
      }
      result += `\t${capitalizedKey} ${type} \`json:"${key}"\`\n`;
    });

    result += '}';
    return result;
  } catch (e) {
    throw new Error('Invalid JSON');
  }
};

export const isValidJson = (json: string): boolean => {
  try {
    JSON.parse(json);
    return true;
  } catch (e) {
    return false;
  }
};

// ─── Flatten helpers ───────────────────────────────────────────────────────────

export interface FlatRow {
  [key: string]: string;
}

/**
 * Flatten any JSON value into an array of flat key-value rows suitable for
 * table / SQL / markdown rendering.
 *
 * - Plain object  → single row with dot-path keys
 * - Array of objects → one row per element, union of all keys
 * - Primitive / other → single row { value: <string> }
 */
export function flattenJson(json: string): { columns: string[]; rows: FlatRow[] } {
  const parsed = JSON.parse(json);

  if (Array.isArray(parsed)) {
    // Array of objects
    if (parsed.length === 0) return { columns: ['(empty)'], rows: [{ '(empty)': '' }] };

    const allRows: FlatRow[] = parsed.map((item) => flattenObject(item));
    const colSet = new Set<string>();
    allRows.forEach((r) => Object.keys(r).forEach((k) => colSet.add(k)));
    const columns = Array.from(colSet);
    // fill missing
    const rows = allRows.map((r) => {
      const row: FlatRow = {};
      columns.forEach((c) => (row[c] = r[c] ?? ''));
      return row;
    });
    return { columns, rows };
  }

  if (typeof parsed === 'object' && parsed !== null) {
    const flat = flattenObject(parsed);
    const columns = Object.keys(flat);
    return { columns, rows: [flat] };
  }

  return { columns: ['value'], rows: [{ value: String(parsed) }] };
}

function flattenObject(obj: unknown, prefix = ''): FlatRow {
  const result: FlatRow = {};

  if (obj === null || obj === undefined) {
    result[prefix || 'value'] = 'null';
    return result;
  }

  if (typeof obj !== 'object') {
    result[prefix || 'value'] = String(obj);
    return result;
  }

  if (Array.isArray(obj)) {
    if (obj.length === 0) {
      result[prefix || 'value'] = '[]';
    } else if (obj.every((v) => typeof v !== 'object' || v === null)) {
      // primitive array – join
      result[prefix || 'value'] = obj.map((v) => (v === null ? 'null' : String(v))).join(', ');
    } else {
      obj.forEach((item, i) => {
        const nested = flattenObject(item, `${prefix}[${i}]`);
        Object.assign(result, nested);
      });
    }
    return result;
  }

  for (const [key, value] of Object.entries(obj as Record<string, unknown>)) {
    const path = prefix ? `${prefix}.${key}` : key;
    const nested = flattenObject(value, path);
    Object.assign(result, nested);
  }

  return result;
}

// ─── SQL Generation ────────────────────────────────────────────────────────────

function sqlType(value: string): string {
  if (value === 'null' || value === '') return 'TEXT';
  if (value === 'true' || value === 'false') return 'BOOLEAN';
  if (/^-?\d+$/.test(value)) return 'INTEGER';
  if (/^-?\d+\.\d+$/.test(value)) return 'REAL';
  return 'TEXT';
}

function sqlEscape(v: string): string {
  if (v === 'null') return 'NULL';
  if (v === 'true') return 'TRUE';
  if (v === 'false') return 'FALSE';
  if (/^-?\d+(\.\d+)?$/.test(v)) return v;
  return `'${v.replace(/'/g, "''")}'`;
}

export function jsonToSql(json: string, tableName: string = 'json_data'): string {
  const { columns, rows } = flattenJson(json);

  const colDefs = columns
    .map((c) => {
      const sample = rows.find((r) => r[c] && r[c] !== 'null' && r[c] !== '');
      const type = sample ? sqlType(sample[c]) : 'TEXT';
      return `  "${c.replace(/"/g, '""')}" ${type}`;
    })
    .join(',\n');

  let sql = `CREATE TABLE "${tableName}" (\n${colDefs}\n);\n\n`;

  rows.forEach((row) => {
    const vals = columns.map((c) => sqlEscape(row[c] ?? '')).join(', ');
    sql += `INSERT INTO "${tableName}" VALUES (${vals});\n`;
  });

  return sql;
}

// ─── Markdown Table ────────────────────────────────────────────────────────────

export function jsonToMarkdownTable(json: string): string {
  const { columns, rows } = flattenJson(json);

  const colWidths = columns.map((c) => {
    const maxData = rows.reduce((mx, r) => Math.max(mx, (r[c] ?? '').length), 0);
    return Math.max(c.length, maxData, 3);
  });

  const pad = (s: string, w: number) => s + ' '.repeat(Math.max(0, w - s.length));

  const header = '| ' + columns.map((c, i) => pad(c, colWidths[i])).join(' | ') + ' |';
  const separator = '| ' + colWidths.map((w) => '-'.repeat(w)).join(' | ') + ' |';
  const body = rows
    .map((r) => '| ' + columns.map((c, i) => pad(r[c] ?? '', colWidths[i])).join(' | ') + ' |')
    .join('\n');

  return `${header}\n${separator}\n${body}`;
}
